---
title: "Lab 5: Data cleaning"
author: "Ruihan He"
date: "10-7-2025"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    highlight: tango
    dev: pdf
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  cache = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 5,
  fig.asp = 0.618,
  fig.align = "center",
  out.width = "80%",
  dpi = 120
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
# Load dataset
towed <- read_rds("towed_vehicles.rds")
```

## Exercises

### Exercise 1
```{r}
library(tidyverse)

towed_renamed <- towed %>%
  rename(
    tow_date = `Tow Date`,
    make = `Make`,
    style = `Style`,
    model = `Model`,
    color = `Color`,
    plate = `Plate`,
    state = `State`,
    towed_to_address = `Towed to Address`,
    tow_facility_phone = `Tow Facility Phone`,
    inventory_number = `Inventory Number`
  )
```




### Exercise 2
```{r}
library(lubridate)
library(tidyverse)

towed_renamed_2 <- towed_renamed %>%
  mutate(tow_date = mdy(tow_date))
```




### Exercise 3
```{r}
tow_make_count <- towed_renamed_2 %>%
  count(make, sort = TRUE) 
```

unique value:nrow(tow_make_count)
count of 1:tow_make_count %>% filter(n == 1)




### Exercise 4
```{r}
tow_make_count_1 <- tow_make_count %>%
  slice(1:20)

tow_make_count_2 <- tow_make_count %>%
  slice(21:40)

tow_make_count_3 <- tow_make_count %>%
  slice(41:60)

tow_make_count_4 <- tow_make_count %>%
  slice(61:n()) 
```




### Exercise 5




### Exercise 6




### Exercise 7




### Exercise 8




## Additional questions

### Question 1




### Question 2




